### ISSUE TITLE
Symlinks are not resolved after a submodule is cloned

### ISSUE THREAD

**Issue by sekunho** [nix-community/naersk#230] opened 2022-04-01 14:49 UTC
Heyah. Thanks for the awesome work!

I have a cargo dependency that contains a submodule, and it doesn't seem like it gets cloned properly by (I think).

Dep's submodule: https://github.com/lambda-fairy/maud/blob/main/maud_macros/src/escape.rs
nix version: 2.5.1
`flake.nix`:

```nix
{
  description = "";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
    naersk.url = "github:nix-community/naersk";
  };

  outputs = { self, nixpkgs, nixos-unstable, flake-utils, naersk }:
    flake-utils.lib.eachSystem [ "x86_64-linux" ] (system:
      let pkgs = nixpkgs.legacyPackages.${system};
           naersk-lib = naersk.lib."${system}".override {
             cargo = pkgs.cargo;
             rustc = pkgs.rustc;
           };
      in
      rec {
        packages.foo = naersk-lib.buildPackage {
          pname = "foo";
          root = ./.;
        };

        defaultPackage = packages.foo;

        apps.foo = flake-utils.lib.mkApp {
          drv = packages.foo;
        };

        defaultApp = apps.foo;

        devShell = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            pkgs.rustc
            pkgs.cargo
          ];
        };
      });
}
```

`nix build` log:

```
Compiling maud_macros v0.23.0 (https://github.com/lambda-fairy/maud?branch=main#e6787cd6)
error: could not compile `maud_macros` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
error[E0583]: file not found for module `escape`
 --> /sources/maud_macros-0.23.0-e6787cd62165a075c7f16a32f8bbacc398f52d13/src/lib.rs:9:1
  |
9 | mod escape;
  | ^^^^^^^^^^^
  |
  = help: to create the module `escape`, create file "/nix/store/shixfmbv64zzi9i0rzb9c8870ydm7cf2-crates-io/maud_macr>


error[E0425]: cannot find function `escape_to_string` in module `escape`
   --> /sources/maud_macros-0.23.0-e6787cd62165a075c7f16a32f8bbacc398f52d13/src/generate.rs:272:17
    |
272 |         escape::escape_to_string(string, &mut self.tail);
    |                 ^^^^^^^^^^^^^^^^ not found in `escape`


error: aborting due to 2 previous errors


Some errors have detailed explanations: E0425, E0583.

For more information about an error, try `rustc --explain E0425`.

[naersk] cargo returned with exit code 101, exiting
```

The strange part is that running `cargo build` directly builds it just fine. I tried looking around the issues, and it doesn't seem like any of the ones I found are exactly this problem. Any pointers are appreciated!

**Comment by Patryk27** [comment] 2022-04-01 15:29
Hi 🙂 

Could you try using naersk from https://github.com/nix-community/naersk/pull/167?

Something like that should work:

```nix
inputs = {
  # ...
  naersk.url = "github:nix-community/naersk?rev=bd4822e754eba04977667ab8a9e5314ae126cc1c";
};
```

... or:

```nix
inputs = {
  # ...
  naersk.url = "github:nix-community/naersk/bd4822e754eba04977667ab8a9e5314ae126cc1c";
};
```

**Comment by Patryk27** [comment] 2022-04-01 16:53
> Am I using it right?

Yeah, looks right; well, thanks for the report, then - I'll try investigating it 🙂

**Comment by Patryk27** [comment] 2022-04-01 17:39
Ah, the issue is that this file is a symlink, and we seem not to be resolving them (so after copying the dependency to `/nix/store`, the symlink remains pointing at `../../maud`, which then is somewhere outside the `/nix/store`); should be fixable 🙂

**Comment by sekunho** [comment] 2022-04-01 17:51
Ahhh okay, that makes sense. Thanks for taking the time to give this a look!

**Comment by sekunho** [comment] 2022-04-15 03:07
Ok, so it turns out submodules aren't relevant in this case. The problem is just that symlinks don't get resolved.

**Comment by Patryk27** [comment] 2022-04-15 07:34
Hi 🙂

Unfortunately I didn't have time yet to investigate this issue more thoroughly, so I don't have any tips - I'll try taking a look some time next week and we'll see.

Btw, I loved your article on creating static binaries!

**Comment by sekunho** [comment] 2022-04-15 08:00
I see, I'll try to look into it to see if I can do anything.

Thank you :smile:.

**Closed** 2022-09-03 15:53 UTC
