### ISSUE TITLE
Issues with `autocxx` in sandbox.

### ISSUE THREAD

**Issue by shymega** [nix-community/naersk#303] opened 2023-08-12 18:02 UTC
Hi,

I'm working on a Flake with `default.nix` for a project called [AIMU][]. My intention is to submit it to nixpkgs (incidentally, does anyone know if Nixpkgs would allow packages using `naersk`?), and I'm having issues with generated `autocxx` files in `target/` during the sandbox phase.

My Flake and `default.nix` can be seen in [my fork's branch][pr], and I was curious if anyone else had experienced a similar error.

I'm not convinced this is a bug, and I would instead create a 'Discussion' in this repo, but it appears to be not enabled.

Thank you!

[AIMU]: https://gitlab.com/awahab/aimu
[pr]: https://gitlab.com/shymega/aimu/-/tree/add-nix-package-support

**Comment by Patryk27** [comment] 2023-08-16 07:34
Hi,

So, in this case it's actually two things overlapping:

1. Naersk has a caching mechanism where it builds all of your dependencies first, then caches their output, and then builds the application itself - it seems it's somewhat misbehaving in your case, but it can be easily turned off:

    ```patch
    diff --git a/default.nix b/default.nix
    index 0a43a4f..d8b3468 100644
    --- a/default.nix
    +++ b/default.nix
    @@ -33,6 +33,7 @@ naersk.lib."${targetPlatform.system}".buildPackage rec {
       copyTarget = true;
       copyLibs = true;
       gitSubmodules = true;
    +  singleStep = true;

       RUST_BACKTRACE = "full";
       LIBCLANG_PATH = lib.makeLibraryPath [ llvmPackages.libclang.lib ];
    ```

2. Flakes [have a quirk](https://github.com/NixOS/nix/issues/6633) related to how they handle Git submodules - using just `nix build` + `./.` creates a source tree _without_ the submodules present, so you have to use:

    ```patch
    diff --git a/flake.nix b/flake.nix
    index e5ce181..822a550 100644
    --- a/flake.nix
    +++ b/flake.nix
    @@ -15,7 +15,7 @@
         in
         {
           overlay = final: prev: {
    -        "${cargoToml.package.name}" = final.callPackage ./. { inherit naersk; };
    +        "${cargoToml.package.name}" = final.callPackage self { inherit naersk; };
           };

           packages = forAllSystems (system:
    ```
    
    ... and then `nix build '.?submodules=1'`.
    
With those two things applied, the compilation fails (I think rightfully) on `main.rs`:

```
error[E0432]: unresolved import `bmi270::config::BMI160_CONFIG_FILE`
 --> src/main.rs:7:14
  |
7 |     config::{BMI160_CONFIG_FILE, BMI260_CONFIG_FILE},
  |              ^^^^^^^^^^^^^^^^^^
  |              |
  |              no `BMI160_CONFIG_FILE` in `config`
  |              help: a similar name exists in the module: `BMI260_CONFIG_FILE`
```

> does anyone know if Nixpkgs would allow packages using `naersk`?

My rough guess - judging by the fact that no Rust package in Nixpkgs is currently built with Naersk - is that they would not allow it :eyes:

(it could be also awkward to use, because Naersk needs Nixpkgs itself, and so using Naersk inside Nixpkgs would introduce a circular dependency: Naersk needs Nixpkgs which need Naersk which needs Nixpkgs [...]).

**Comment by shymega** [comment] 2023-08-21 23:57
Hey!

Thanks for looking into this. I managed to get it building up to the error you encountered. This is because a dependency is being refactored. It's expected behaviour.

With regards to the special `nix build` invocation - is there, not a way to do that in the `flake.nix` itself?

I was thinking of submitting the package to Nixpkgs, but I'll need to look into a different way to package this Rust tool. I really like `Nearsk`.

**Comment by Patryk27** [comment] 2023-09-05 07:29
> is there, not a way to do that in the flake.nix itself?

There's no other way when you use a flake, _but_ if you use something like `pkgs.fetchFromGithub` or `builtins.fetchGit` (which you would normally use when submitting a package to nixpkgs anyway), they should work correctly 🙂 

You can pair them with Naersk as well - i.e. something like this should work:

```
naersk.buildPackage {
  src = pkgs.fetchFromGithub {
    fetchSubmodules = true;
    # ...
  };
}
```

To keep the issue tracker tidy, I'm going to close this issue here, but feel free to ask if you stumble upon anything 🙂

**Closed by Patryk27** 2023-09-05 07:29 UTC

**Comment by shymega** [comment] 2023-09-05 18:14
Sorry to bump this. One more question.

Can the Flake 'source' build from the local working directory? I.e, something like `src = fetchGit "./.";`? I've been trying that, with different variations, and I see this error, mostly:

```shelll
warning: Git tree '/home/dzr/projects/git.shymega.org.uk/shymega/AIMU' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'aimu-0.2.1'
         whose name attribute is located at /nix/store/kppl0knhr8p67sjfgbxdwbnw7yawggfw-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'cargoconfig' of derivation 'aimu-0.2.1'

         at /nix/store/ffa6yxld9ynzdj53cvfg2g4hxi79p1ca-source/build.nix:90:5:

           89|     # and git dependencies.
           90|     cargoconfig = builtinz.toTOML {
             |     ^
           91|       source = {

       error: value is a string while a set was expected```

I couldn't tell if `builtinz` was a typo...

**Comment by Patryk27** [comment] 2023-09-06 07:23
Yeah, `src = fetchGit { ... }` should work - could you show more code? :eyes:

> I couldn't tell if `builtinz` was a typo...

Nah, just a convention - it's like Nix's `builtins` but with extra stuff (e.g. to serialize / deserialize TOMLs) :smile:

**Comment by shymega** [comment] 2023-09-08 23:11
> Yeah, `src = fetchGit { ... }` should work - could you show more code? 👀
> 
> > I couldn't tell if `builtinz` was a typo...
> 
> Nah, just a convention - it's like Nix's `builtins` but with extra stuff (e.g. to serialize / deserialize TOMLs) 😄

So, this is what I'm using:

```nix
{ lib
, naersk
, stdenv
, clangStdenv
, hostPlatform
, targetPlatform
, pkg-config
, libiconv
, rustfmt
, cargo
, rustc
, llvmPackages
, libcxx
, glibc
}:

let
  cargoToml = (builtins.fromTOML (builtins.readFile ./Cargo.toml));
in

naersk.lib."${targetPlatform.system}".buildPackage rec {
  src = builtins.fetchGit {
    url = "./";
    submodules = true;
  };

  buildInputs = [
    rustfmt
    pkg-config
    cargo
    rustc
  ];
  checkInputs = [ cargo rustc ];

  doCheck = true;
  copyTarget = true;
  copyLibs = true;
  gitSubmodules = true;
  singleStep = true;

  RUST_BACKTRACE = "full";
  LIBCLANG_PATH = lib.makeLibraryPath [ llvmPackages.libclang.lib ];
  BINDGEN_EXTRA_CLANG_ARGS = [
    ''-I"${glibc.dev}/include"''
    ''-I"${libcxx.dev}/include/c++/v1"''
    ''-I"${llvmPackages.libclang.lib}/lib/clang/${llvmPackages.libclang.version}/include"''
  ];

  name = cargoToml.package.name;
  version = cargoToml.package.version;

  meta = with lib; {
    #    description = cargoToml.package.description;
    #    homepage = cargoToml.package.homepage;
    #    license = with licenses; [ mit ];
    maintainers = with maintainers; [ ];
  };
}
```

The Flake calls the above snippet, which is in `default.nix`.

The error I get is rather cryptic - although I find I am getting somewhat better at understanding Nix...

```shell
❯ nix build
warning: Git tree '/home/dzr/projects/git.shymega.org.uk/shymega/AIMU' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'aimu-0.2.1'
         whose name attribute is located at /nix/store/kppl0knhr8p67sjfgbxdwbnw7yawggfw-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'cargoconfig' of derivation 'aimu-0.2.1'

         at /nix/store/ffa6yxld9ynzdj53cvfg2g4hxi79p1ca-source/build.nix:90:5:

           89|     # and git dependencies.
           90|     cargoconfig = builtinz.toTOML {
             |     ^
           91|       source = {

       error: file:// URL 'file://./' has unexpected authority '.'
```

Bug, maybe?

**Comment by Patryk27** [comment] 2023-09-09 06:37
I think you would have to use ./ without the quotes, otherwise it’s treated as a string instead of a path.

**Comment by shymega** [comment] 2023-09-09 15:47
> I think you would have to use ./ without the quotes, otherwise it’s treated as a string instead of a path.

Sorry, should have mentioned that I did try that. I've attached the error output below. It's very strange.

```shell
❯ nix build
warning: Git tree '/home/dzr/projects/git.shymega.org.uk/shymega/AIMU' is dirty
error:
       … while evaluating the attribute 'aimu'

         at /nix/store/xl1cn4wm7pinf7m9494vfy1p110pxpvk-source/flake.nix:18:9:

           17|       overlay = final: prev: {
           18|         "${cargoToml.package.name}" = final.callPackage self { inherit naersk; };
             |         ^
           19|       };

       … while evaluating a branch condition

         at /nix/store/kppl0knhr8p67sjfgbxdwbnw7yawggfw-source/lib/customisation.nix:179:8:

          178|
          179|     in if missingArgs == [] then makeOverridable f allArgs else abort error;
             |        ^
          180|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: syntax error, unexpected '.'

       at /nix/store/xl1cn4wm7pinf7m9494vfy1p110pxpvk-source/default.nix:23:11:

           22|   src = builtins.fetchGit {
           23|     url = ./;
             |           ^
           24|     submodules = true;
```

**Comment by Patryk27** [comment] 2023-09-09 17:44
It should be `./.` :eyes: (same way you had it initially, in `final.callPackage ./. { inherit naersk; };`).

**Comment by shymega** [comment] 2023-09-09 17:55
Ah, that's gotten me somewhere! Sorry, missed that.

Got a new error, but this is due to purity. I think an easier solution would be just to fetch from Git. On the other hand, this makes testing locally tricky. I need to re-evaluate the usage of Nix and friends in this repo, anyway.

(Logs:

```shell
❯ nix build
warning: Git tree '/home/dzr/projects/git.shymega.org.uk/shymega/AIMU' is dirty
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'aimu-0.2.1'
         whose name attribute is located at /nix/store/kppl0knhr8p67sjfgbxdwbnw7yawggfw-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'cargoconfig' of derivation 'aimu-0.2.1'

         at /nix/store/ffa6yxld9ynzdj53cvfg2g4hxi79p1ca-source/build.nix:90:5:

           89|     # and git dependencies.
           90|     cargoconfig = builtinz.toTOML {
             |     ^
           91|       source = {

       error: in pure evaluation mode, 'fetchTree' requires a locked input, at «none»:0
```)

**Comment by Patryk27** [comment] 2023-09-09 18:34
For testing locally, you can always try `nix build --impure` 😈 
Or use `nix-build` instead of Flakes (i.e. the older way).

**Comment by shymega** [comment] 2023-09-09 19:47
It seems that did get a bit further, but failed to build.

I've pushed my commits to a branch - https://gitlab.com/shymega/aimu/-/tree/nix-flake-test-1?ref_type=heads.

I don't know if it's a bug with `naersk`, but it might be worth looking into in case it affects other people. Thank you for your time with my issue, though!

The shell output is below:

```shell
❯ nix build --impure
warning: Git tree '/home/dzr/projects/git.shymega.org.uk/shymega/AIMU' is dirty
evaluating derivation 'git+file:///home/dzr/projects/git.shymega.org.uk/shymegafatal: '/nix/store/xawf37pd3rmqdlvqahi7ysvfrchc73y6-source' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
warning: could not read HEAD ref from repo at 'file:///nix/store/xawf37pd3rmqdlvqahi7ysvfrchc73y6-source', using 'master'
evaluating derivation 'git+file:///home/dzr/projects/git.shymega.org.uk/shymegafatal: '/nix/store/xawf37pd3rmqdlvqahi7ysvfrchc73y6-source' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error:
       … while calling the 'derivationStrict' builtin

         at //builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'aimu-0.2.1'
         whose name attribute is located at /nix/store/kppl0knhr8p67sjfgbxdwbnw7yawggfw-source/pkgs/stdenv/generic/make-derivation.nix:303:7

       … while evaluating attribute 'cargoconfig' of derivation 'aimu-0.2.1'

         at /nix/store/ffa6yxld9ynzdj53cvfg2g4hxi79p1ca-source/build.nix:90:5:

           89|     # and git dependencies.
           90|     cargoconfig = builtinz.toTOML {
             |     ^
           91|       source = {

       error: program 'git' failed with exit code 128
```

**Comment by Patryk27** [comment] 2023-09-26 14:41
Hi, sorry for late answer 😅 

So, this is caused by the fact that doing:
```
src = builtins.fetchGit {
  url = ./.;
  submodules = true;
};
```
... first evaluates `./.` that copies stuff into `/nix/store` _already ignoring_ the `.git` directory (that's just how it works); then `builtins.fetchGit` is evaluated on that `/nix/store/...` path that doesn't contain `.git`, causing it to fail.

If you want to go with `./.`, the only approach (that I know of) is the one I mentioned at the beginning - but you can also do something like:

```
src = builtins.fetchGit {
  url = "https://gitlab.com/shymega/aimu";
  rev = "630b12bdb2354722dae56a55093ee1ccdafa9009";
  submodules = true;
  allRefs = true; # so that it's possible to refer to an arbitrary commit
};
```

... which will download the submodules correctly.

**Comment by shymega** [comment] 2023-10-04 23:23
Yeah, I think I might package AIMU as a Nixpkg, so I wouldn't be relying on Naersk at that point, anyway. Your explanation is sound though, so thank you for taking the time to help!
